inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*

Documentation:
  Enabled: false
  
Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

#Ruby2.3から’# frozen_string_literal: true’マジックコメントを使うと文字列リテラルがfreezeになる
#Ruby3.0から文字列リテラルはfeeze
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/CommentIndentation:
  Exclude:
    - app/admin/*