inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*

Documentation:
  Enabled: false
  
Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*